# Generated by Django 5.0.6 on 2024-06-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('acesso_nivel_1', models.BooleanField(default=False)),
                ('acesso_nivel_2', models.BooleanField(default=False)),
                ('acesso_nivel_3', models.BooleanField(default=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
        migrations.CreateModel(
            name='unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Endereço', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Inicio', models.CharField(max_length=100)),
                ('Fim', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=100)),
                ('id_res', models.CharField(max_length=100)),
                ('Responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Nome', models.CharField(max_length=100)),
                ('Atividade', models.CharField(max_length=100)),
                ('Tarefa', models.CharField(max_length=100)),
                ('Pessoa', models.CharField(max_length=100)),
                ('Comportamento', models.CharField(max_length=100)),
                ('Movimento', models.CharField(max_length=100)),
                ('Posição', models.CharField(max_length=100)),
                ('EPI', models.CharField(max_length=100)),
                ('Ambiente', models.CharField(max_length=100)),
                ('Padrão', models.CharField(max_length=100)),
                ('Organização', models.CharField(max_length=100)),
                ('Descrição', models.CharField(max_length=100)),
                ('Correção', models.CharField(max_length=100)),
                ('Data', models.CharField(max_length=100)),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
                ('Setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor')),
                ('Turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='estratificação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=100)),
                ('Data_ocorrencia', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('Sexo', models.CharField(max_length=100)),
                ('Idade', models.CharField(max_length=100)),
                ('Hora', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('Nome', models.CharField(max_length=100)),
                ('Setor_a', models.CharField(max_length=100)),
                ('Data_ad', models.CharField(max_length=100)),
                ('tempo_emp', models.CharField(max_length=100)),
                ('Resumo', models.CharField(max_length=200)),
                ('Lider', models.CharField(max_length=100)),
                ('Supervisor', models.CharField(max_length=100)),
                ('Area_fe', models.CharField(max_length=100)),
                ('Tipo_lesão', models.CharField(max_length=100)),
                ('Causador', models.CharField(max_length=100)),
                ('D_fastamento', models.CharField(max_length=100)),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
                ('Setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor')),
                ('Turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno')),
                ('Unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='Unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidade'),
        ),
    ]
